ALTER TABLE users ADD COLUMN telegram_chat_id TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN telegram_company_id INTEGER DEFAULT NULL REFERENCES companies(id);

CREATE TABLE IF NOT EXISTS telegram_link_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    token TEXT UNIQUE NOT NULL,
    used INTEGER NOT NULL DEFAULT 0,
    expires_at DATETIME NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
